# linear regression

In [44]:
import numpy as np

In [84]:
X = np.random.randint(0, 100, size=(100, 2))

In [85]:
X.shape

(100, 2)

In [86]:
X[:10]

array([[56, 72],
       [ 0, 21],
       [19, 74],
       [41, 10],
       [21, 38],
       [96, 20],
       [44, 93],
       [39, 14],
       [26, 81],
       [90, 22]])

In [87]:
np.random.seed(0)

In [88]:
eps = np.random.randn(X.shape[0], 1)/0.1
eps[:10]

array([[17.64052346],
       [ 4.00157208],
       [ 9.78737984],
       [22.40893199],
       [18.6755799 ],
       [-9.7727788 ],
       [ 9.50088418],
       [-1.51357208],
       [-1.03218852],
       [ 4.10598502]])

In [89]:
eps.T.dot(eps)

array([[10194.03617937]])

In [90]:
a1 = 3.2
a2 = 1.8
a0 = 0.4

In [91]:
# eps = 0

In [94]:
(a1 * X[:,0]).shape, eps.shape

((100,), (100, 1))

In [122]:
y = (a1 * X[:,0] + a2 * X[:,1] + a0 + eps[:,0]).reshape(-1, 1)
y.shape

(100, 1)

In [123]:
y[:10]

array([[326.84052346],
       [ 42.20157208],
       [204.18737984],
       [172.00893199],
       [154.6755799 ],
       [333.8272212 ],
       [318.10088418],
       [148.88642792],
       [228.36781148],
       [332.10598502]])

In [124]:
import matplotlib.pyplot as plt

In [125]:
a1, a0

(3.2, 0.4)

# use scikit learn

In [126]:
from sklearn.linear_model import LinearRegression

In [127]:
lr = LinearRegression()

In [128]:
lr.fit(X, y)

LinearRegression()

In [129]:
lr.coef_, lr.intercept_

(array([[3.20550943, 1.85061222]]), array([-1.7622443]))

In [130]:
a1, a2, a0

(3.2, 1.8, 0.4)

# recover without scikit learn

In [131]:
np.random.seed(3)

In [132]:
b0 = np.random.randn()
b0

1.7886284734303186

In [133]:
b1 = np.random.randn()
b1

0.43650985051198943

In [134]:
b2 = np.random.randn()
b2

0.09649746807200862

In [135]:
a1, a2, a0

(3.2, 1.8, 0.4)

In [136]:
theta_a = np.array([a0, a1, a2]).reshape(1, 3)
theta_b = np.array([b0, b1, b2]).reshape(1, 3)

In [137]:
theta_a, theta_b

(array([[0.4, 3.2, 1.8]]), array([[1.78862847, 0.43650985, 0.09649747]]))

In [138]:
X_b = np.c_[np.ones((100, 1)), X]

In [139]:
X_b[:10]

array([[ 1., 56., 72.],
       [ 1.,  0., 21.],
       [ 1., 19., 74.],
       [ 1., 41., 10.],
       [ 1., 21., 38.],
       [ 1., 96., 20.],
       [ 1., 44., 93.],
       [ 1., 39., 14.],
       [ 1., 26., 81.],
       [ 1., 90., 22.]])

In [140]:
X_b.shape

(100, 3)

In [143]:
theta_a.shape, theta_b.shape, y.shape

((1, 3), (1, 3), (100, 1))

In [144]:
res_a = X_b.dot(theta_a.T) - y
res_a.shape

(100, 1)

In [145]:
res_a[:10]

array([[-17.64052346],
       [ -4.00157208],
       [ -9.78737984],
       [-22.40893199],
       [-18.6755799 ],
       [  9.7727788 ],
       [ -9.50088418],
       [  1.51357208],
       [  1.03218852],
       [ -4.10598502]])

In [146]:
loss_a = res_a.T.dot(res_a)
loss_a

array([[10194.03617937]])

In [147]:
res_b = X_b.dot(theta_b.T) - y
res_b[:10]

array([[-293.65952566],
       [ -38.38649678],
       [-186.96425157],
       [-151.35842497],
       [-140.05334078],
       [-288.20369772],
       [-288.13155775],
       [-128.72295072],
       [-207.41363198],
       [-288.9085257 ]])

In [148]:
loss_b = res_b.T.dot(res_b)
loss_b

array([[5581465.96557398]])

In [153]:
def step(theta_b, alpha):
    d_theta = (y - X_b.dot(theta_b.T)) * X_b / X_b.shape[0]
    
    theta_b += alpha * np.sum(d_theta, axis=0).reshape(1, 3)

    res_b = X_b.dot(theta_b.T) - y
    loss_b = res_b.T.dot(res_b)
    return theta_b, theta_a, loss_b

In [154]:
theta_b.shape

(1, 3)

In [155]:
theta_b

array([[1.78862847, 0.43650985, 0.09649747]])

In [156]:
theta_b, theta_a, loss = step(theta_b, 5.0e-5)

In [157]:
for i in range(10):
    theta_b, theta_a, loss = step(theta_b, 5.0e-5)
print(theta_b, theta_a, loss)

[[1.82655371 2.79992145 2.06830571]] [[0.4 3.2 1.8]] [[31387.00313275]]


In [158]:
for i in range(100):
    theta_b, theta_a, loss = step(theta_b, 1.0e-5)
print(theta_b, theta_a, loss)

[[1.82710071 3.0438514  1.94834942]] [[0.4 3.2 1.8]] [[13085.22527058]]


In [159]:
for i in range(10):
    theta_b, theta_a, loss = step(theta_b, 1.0e-6)
print(theta_b, theta_a, loss)

[[1.82709569 3.0449928  1.94723159]] [[0.4 3.2 1.8]] [[13034.20013444]]
